name = "Catlab"
uuid = "134e5e36-593f-5add-ad60-77f754baafbe"
license = "BSD2"
authors = ["Evan Patterson <epatters@stanford.edu>"]
version = "0.2.3"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnionFind = "99c6138d-4661-531e-8606-19bf1ec96588"

[compat]
julia = "1.0"
LightGraphs = ">= 1.3"

[extras]
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
