name = "Catlab"
uuid = "134e5e36-593f-5add-ad60-77f754baafbe"
license = "BSD2"
authors = ["Evan Patterson <evan@epatters.org>"]
version = "0.6.2"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AutoHashEquals = "^0"
Compat = "^1, ^2, ^3"
Compose = "^0"
DataStructures = "^0"
IterativeSolvers = "^0"
JSON = "^0"
LightGraphs = "^1.3"
LightXML = "^0"
LinearMaps = "^2"
LinearOperators = "^1.0"
Match = "^1"
MetaGraphs = "^0.6"
Parameters = "^0"
Reexport = "^0"
Requires = "^1"
StaticArrays = "^0"
julia = "1.0"

[extras]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
