name = "Catlab"
uuid = "134e5e36-593f-5add-ad60-77f754baafbe"
license = "MIT"
authors = ["Evan Patterson <evan@epatters.org>"]
version = "0.12.3"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
AutoHashEquals = "0.2"
Compose = "0.7, 0.8, 0.9"
DataStructures = "0.17, 0.18"
FunctionWrappers = "1.1.2"
GeneralizedGenerated = "0.2, 0.3"
JSON = "0.20, 0.21"
LightXML = "0.8, 0.9"
MLStyle = "0.4"
PrettyTables = "0.12, 1.0"
Reexport = "0.2, 1.0"
Requires = "^1"
StaticArrays = "0.12, 1.0"
Tables = "^1"
TypedTables = "^1"
julia = "1.6"

[extras]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Graphviz_jll = "3c863552-8265-54e4-a6dc-903eb78fde85"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
